// Recipes
export const ADD_RECIPE = "ADD_RECIPE";
export const DATA_LOADED = "DATA_LOADED";
export const NAME_ALREADY_EXISTS = "NAME_ALREADY_EXISTS";
export const RECIPE_VALIDATION_ERROR = "RECIPE_VALIDATION_ERROR";
export const UPDATE_RECIPE_ATTRIBUTES = "UPDATE_RECIPE_ATTRIBUTES";
export const SAVE_RECIPE_SUCCESS = "SAVE_RECIPE_SUCCESS";
export const SAVE_RECIPE_FAILURE = "SAVE_RECIPE_FAILURE";
export const CLEAR_RECIPE = "CLEAR_RECIPE";

// Users
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER_ATTRIBUTES = "UPDATE_USER_ATTRIBUTES";
export const USER_VALIDATION_ERROR = "USER_VALIDATION_ERROR";
